### ISSUE TITLE
Solus version? :point_right::point_left: 

### ISSUE THREAD

**Issue by sammypanda** [LinuxEuphony/vmware-host-modules-builder-cli#11]
the getsol.us forums are down so im stranded and the methods don't work :3

**Comment by david-kariuki** [comment]
Hi @sammypanda 
I have not done a Solus version, but you could follow this up with [@mkubecek](https://github.com/mkubecek) or check out his [vmware-host-modules](https://github.com/mkubecek/vmware-host-modules) repo for a patch

**Comment by sammypanda** [comment]
> wont fix

**Comment by david-kariuki** [comment]
Hi @sammypanda 
How did it go? Did you get the patch package for souls?

**Comment by sammypanda** [comment]
i think i recall getting a patch package but i had some issue and ended up finding another way around

**Comment by david-kariuki** [comment]
Ok
