### ISSUE TITLE
Adding linux-headers as dependent packages

### ISSUE THREAD

**Issue by tammyTUX** [LinuxEuphony/vmware-host-modules-builder-cli#6]
Sometimes I miss installing correct linux-headers prior running your wonderful script. Maybe you could a them as dependent packages?
e.g. something like that for Debian
```
kernelversiononly=$(uname -r) && apt-get install linux-headers-$(uname -r) linux-headers-${kernelversiononly::-5}common -y
```
I know its not the best way, but simple und working.

Kind regards

**Comment by david-kariuki** [comment]
Hello, I will look into this. What Linux distro are you using?

**Comment by tammyTUX** [comment]
Debian Unstable

**Comment by david-kariuki** [comment]
I have updated the code to reflect your suggestion. Thank you for this
